### ISSUE TITLE
ScoreBoard not showing up!

### ISSUE THREAD

**Issue by xXMartoBgXx** [yPedx/SpigotBoard#1]
I installed the plugin and the Scoreboard is not showing up, also typed /scoreboard and it always says that its disabled.. Please help!

**Comment by yPedx** [comment]
Sorry for the late reply! Are there any errors? What version is your server?
Please post them on pastebin.com and leave the link here.

**Comment by yPedx** [comment]
I experienced it myself, should be fixed in the newest version! Come back and tell me if it doens't help!
