### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by Ronnie0982** [yPedx/SpigotBoard#10]
Hey
After sometime testing the plugin, i found out that the update time on the scoreboard doesn't work?
And even doe my config is set to 1 second it doesn't work

`  interval-seconds: 1`

Edit:
It looks like it's the coords that takes some time to load...

**Comment by yPedx** [comment]
Does the problem still presist or has it been solved?

**Comment by Ronnie0982** [comment]
No it has been a little ustable with the coords
But the countdown goes down every second :)
