### ISSUE TITLE
Timezones?

### ISSUE THREAD

**Issue by KIKONUTINO** [yPedx/SpigotBoard#11]
Do you know the correct timezone for Spain/Madrid? Thank you :D

**Comment by yPedx** [comment]
Just do a quick google search.
https://www.google.com/search?rlz=1C1TIGY_enNO692NO692&ei=y6IAWuX1HMGF6ASvgoyYCw&q=Timezone+Spain/Madrid&oq=Timezone+Spain/Madrid&gs_l=psy-ab.3..0i10i30k1j0i8i10i30k1.14357.14614.0.14724.2.2.0.0.0.0.80.145.2.2.0....0...1.1.64.psy-ab..0.2.144...0i13i10i30k1j0i8i13i10i30k1.0.qs-y-CL3YPM&gws_rd=cr&dcr=0

**Comment by KIKONUTINO** [comment]
Lel... I meant to put it on the config... Which is the correct thing to put here? 
  timezone: America/New_York
So my players get the Spain/Madrid time

**Comment by yPedx** [comment]
Well, isn't that Spain/Madrid then?
