### ISSUE TITLE
Make it so you can change money format

### ISSUE THREAD

**Issue by Slimenamedjerry** [yPedx/SpigotBoard#12]
I was wondering if you could tell me if there was a way to format money as $1,000,000 (or 1M, 1.2M etc) instead of 1000000 on the scoreboard. I find this hard to read and wanted it with commas to make it easier for everyone. If not then is it possible that it could be added?

thank you

**Comment by yPedx** [comment]
You can set this if you download the Vault expansion for PlaceholderAPI. No, not the plugin itself.
