### ISSUE TITLE
What's wrong with my config? (SpigotBoard)

### ISSUE THREAD

**Issue by Kreeper1295** [yPedx/SpigotBoard#14]
Hello there,

I had just recently installed the plugin (SpigotBoard), but after I configured it the scoreboard wouldn't show up. Even if I disabled it or enabled it. Something's obviously wrong with my config. Can you take a look?

[config.txt](https://github.com/yPedx/SpigotBoard/files/1608521/config.txt)

(I had to convert the yml file to a txt so I could upload. The original file is a yml)

**Comment by yPedx** [comment]
Do you have any errors in your console? if so, please copy it and upload as .txt file too.

**Comment by Kreeper1295** [comment]
There are some errors from other plugins, but I should be able to fix those.

[latest.txt](https://github.com/yPedx/SpigotBoard/files/1609147/latest.txt)

**Comment by yPedx** [comment]
Seems like SpigotBoard is trying to get the balance of a player, but returns an error -because:
This is what your console says: "Essentials API is called before Essentials is loaded."
If you fix the problem with your Essentials, SpigotBoard will also work.
