### ISSUE TITLE
Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by cPathz** [yPedx/SpigotBoard#16]
I get this error

Spigot Version:
CraftBukkit version git-Spigot-eadd615-4509a14 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Spigotboard Version: 2.2.0

`16.04 22:26:28 [Server] ERROR Could not load 'plugins/SpigotBoard v2.2.0.jar' in folder 'plugins'
16.04 22:26:28 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/developer/ypedx/SpigotBoard has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
16.04 22:26:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161] 16.04 22:26:28 [Server] INFO Caused by: java.lang.UnsupportedClassVersionError: me/developer/ypedx/SpigotBoard has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
16.04 22:26:28 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
16.04 22:26:28 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_161]
16.04 22:26:28 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_161]
16.04 22:26:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
16.04 22:26:28 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
16.04 22:26:28 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
16.04 22:26:28 [Server] INFO at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161]
16.04 22:26:28 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[CorpMore.jar:git-Spigot-eadd615-4509a14]
16.04 22:26:28 [Server] INFO ... 6 more`

**Comment by yPedx** [comment]
Are you using Java 8 or Java 9 for your server?

**Comment by cPathz** [comment]
Right. im runing Java 1.8.0_161-0.b14.el7_4.x86_64/jre

thanks to you for your work

**Comment by yPedx** [comment]
I suggest installing Java 9 for your server, not sure if SpigotBoard with Java 8 will be available in a while.

**Comment by yPedx** [comment]
Should be fixed in the latest version, thanks for reporting!
