### ISSUE TITLE
Not working with any Tablist Plugins

### ISSUE THREAD

**Issue by cvtli** [yPedx/SpigotBoard#19]
Hey,
Your Plugin is great, but It is not working with Tablist -or Nametag Plugins. Could you take a look at that?
When I got a Tablist Plugin the names just return to white color for a few seconds, and then the prefix shows up for a few seconds. Its pending all time and idk what to do about that

Kind regards

**Comment by yPedx** [comment]
I haven't experienced any of your issues before, even though I only use a custom tablist and scoreboard. What plugins are you using?
