### ISSUE TITLE
Incompatible with Citizens Plugin

### ISSUE THREAD

**Issue by blackphreak** [yPedx/SpigotBoard#2]
When your plugin is loaded, it will override the Citizens (NPC Teams), which makes Citizens do not show the npc name anymore until I disable your plugin and reload Citizens (in order to regenerate those NPCs).

When I enable your plugin again, it start to override the NPC name again...so, please fix this, thx.

I don't know if this works or not, but I think you can try to fix the bug with this:

use :
Bukkit.getServer().getScoreboardManager().getMainScoreboard();
to replace this :
Bukkit.getServer().getScoreboardManager().getNewScoreboard();
Spigot Version: 1.12-R0.1-SNAPSHOT
Ref.: https://github.com/CitizensDev/Citizens2/blob/81457511369ed332209dd73ad033a19ca565b810/v1_12_R1/src/main/java/net/citizensnpcs/nms/v1_12_R1/entity/HumanController.java

**Comment by yPedx** [comment]
Sorry for the very late reply, I'll see what I can do about it :)

**Comment by blackphreak** [comment]
Hope u can fix this very soon!!~

**Comment by yPedx** [comment]
I did a few fixes and changes in the newest version, however: I tried as you said but I couldn't get it to work, and I don't really have time atm to try and get it to work. If it doesn't fix the problem, ping me and I'll see what more can be done :)

**Comment by blackphreak** [comment]
How about may I have your source code? I would like to try to fix this by myself.
If I fixed it, I will Create a Pull Request here for u to update ur plugin.

**Comment by blackphreak** [comment]
I think you can take a look at this in order to solve the problem :
https://www.youtube.com/watch?v=bkBXkAc3Wp0

btw, if you want to, I can send u my source code later. (I did a experiment myself)

**Comment by blackphreak** [comment]
y dont u take a look for this bug fix lol...
