### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by JonesManYouTube** [yPedx/SpigotBoard#20]
When i change the Timezone the plugin does not work. Can you tell me what i should enter when i want the Timezone of Berlin.

**Comment by yPedx** [comment]
Does it leave an error when you try to change it? If so, please show me that error using https://pastebin.com/

You may find a list of timezones https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[here]. Timezones are highlighted in blue and red to the left.
