### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by tigerboy985** [yPedx/SpigotBoard#24]
Does this work for 1.7.10/1.7.9
And if it does is it possible to set it to a players faction name, balance and the server IP?

**Comment by yPedx** [comment]
Yes, it does work for 1.7 - but, you'd have to sacrifice the length of your scoreboard. There will also be no support for 1.7 issues as SpigotBoard is not meant for any version lower than 1.8.
Variables are limited by PlaceholderAPI for the time being.

**Comment by tigerboy985** [comment]
So would I be able to put the faction name, their balance and the server Ip in then?

**Comment by tigerboy985** [comment]
Also the scoreboard isn't showing
