### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by tigerboy985** [yPedx/SpigotBoard#25]
2 Things. I installed this into my 1.7 server and it installed fine. I tried to enable the scoreboard by changing the command and it still didn't work. I also am unsure of what to put in the config for what I want - I want it to say: 
Welcome
{Player}

Faction:
{Faction}

Balance:
{balance}

Server IP:
{IP}

**Comment by yPedx** [comment]
As I said, yes it works on 1.7, but that doesn't mean it has all the features of a 1.8 scoreboard.
How you can edit the scoreboard is already in the config file, it shouldn't be hard to change it up.
Some of the {variables} you want, are defined in PlaceholderAPI's own documentation - https://www.spigotmc.org/wiki/placeholderapi-placeholders/
