### ISSUE TITLE
Flashing Scoreboard

### ISSUE THREAD

**Issue by HeyItzRye** [yPedx/SpigotBoard#26]
When I loaded the plugin, the scoreboard randomly flashes on and off, and I can't get it to stop, I reloaded the plugin, and it continues to do the same. #############################################################
# ____        _             _   ____                      _ #
#/ ___| _ __ (_) __ _  ___ | |_| __ )  ___   __ _ _ __ __| |#
#\___ \| '_ \| |/ _` |/ _ \| __|  _ \ / _ \ / _` | '__/ _` |#
# ___) | |_) | | (_| | (_) | |_| |_) | (_) | (_| | | | (_| |#
#|____/| .__/|_|\__, |\___/ \__|____/ \___/ \__,_|_|  \__,_|#
#      |_|      |___/                                       #
#############################################################

# Wiki: https://github.com/yPedx/SpigotBoard/wiki
#
# Report issues: https://github.com/yPedx/SpigotBoard/issues
#
# title = title of scoreboard.
# text = scoreboard lines.
#
# Color codes are supported.
#
# List of all compatible variables can be found on the wiki page.

# Empty lines can be achieved by doing this: '' (as shown below)
Scoreboard: 
  title: '&cSpigot&7Board'
  text: 
    - '&8� &cPlayer'
    - '&7{Player}'
    - ''
    - '&8� &cRank'
    - '&7{Group}'
    - ''
    - '&8� &cTime'
    - '&7{Time}'
    - ''
    - '&8� &cOnline'
    - '&7{Online}/{MaxPlayers}'
    - ''
    - '&7Remember to'
    - '&7visit the &cwiki&7!'

Settings:
  timezone: America/New_York
  time-format: 'HH:mm'
  toggleCommand: 'scoreboard'
  disabled-worlds:
  interval-seconds: 7
  update-reminder: true
  disable-stats: false

**Comment by yPedx** [comment]
If it's flashing continously without a 7 second interval (as you have specified in your config), I'll have a look. If it **is** flashing every 7 seconds, It's caused by the scoreboard refreshing. I'll be working on a fix for it soon.
