### ISSUE TITLE
PEXTablist issue

### ISSUE THREAD

**Issue by Davidmayr** [yPedx/SpigotBoard#27]
I use the plugin https://www.spigotmc.org/resources/pex-tablist-and-nametags.20111/
And when i join everything showes up correctly but when the scoreboard loades the plugin doesnt show enything anymore! Please fix that!

**Comment by yPedx** [comment]
If you read the description of that plugin, you would know that it would not work correctly if there's another plugin using scoreboards. If the plugin were to be using another method to set the color or name, it would work fine with SpigotBoard.
