### ISSUE TITLE
Placeholders is not working in titile

### ISSUE THREAD

**Issue by aBo0oDGamer** [yPedx/SpigotBoard#3]
Hi,
i have just download the plugin
and i tried to add placeholder in scoreboard title but its not working its show the same placeholder
can u fix it ? and thanks

**Comment by yPedx** [comment]
Have you installed the extensions/plugins required for the placeholder to work?

**Comment by yPedx** [comment]
Should be fixed in the latest version. https://www.spigotmc.org/resources/spigotboard.47497/
