### ISSUE TITLE
PlacehoderAPI

### ISSUE THREAD

**Issue by Lightcaster5** [yPedx/SpigotBoard#31]
I don't know if I am doing something wrong but I tried using one of the placeholders provided by PlaceholderAPI and it didn't work. The "Health" Part of it is messing up.

Config:
#############################################################
# ____        _             _   ____                      _ #
#/ ___| _ __ (_) __ _  ___ | |_| __ )  ___   __ _ _ __ __| |#
#\___ \| '_ \| |/ _` |/ _ \| __|  _ \ / _ \ / _` | '__/ _` |#
# ___) | |_) | | (_| | (_) | |_| |_) | (_) | (_| | | | (_| |#
#|____/| .__/|_|\__, |\___/ \__|____/ \___/ \__,_|_|  \__,_|#
#      |_|      |___/                                       #
#############################################################

# Wiki: https://github.com/yPedx/SpigotBoard/wiki
#
# Report issues: https://github.com/yPedx/SpigotBoard/issues
#
# title = title of scoreboard.
# text = scoreboard lines.
#
# Color codes are supported.
#
# List of all compatible variables can be found on the wiki page.

# Empty lines can be achieved by doing this: '' (as shown below)
Scoreboard: 
  title: '&3GIANTSON&bPVP'
  text: 
    - '&bStats:'
    - '  &7- &3Money: &b{Money}'
    - '  &7- &3Kills: &b{Kills}'
    - '  &7- &3Deaths: &b{Deaths}'
    - '  &7- &3Health: &b%player_health%'
    - '  &7- &3Rank: &b{Group}'

Settings:
  timezone: America/New_York
  time-format: 'HH:mm'
  toggleCommand: 'scoreboardtoggle'
  disabled-worlds:
    - disabledworld
    - disabledworld2
  interval-seconds: 1
  update-reminder: true
  disable-stats: false

**Comment by artemati1** [comment]
Just reload placeholdersapi plugin.

**Comment by yPedx** [comment]
I'm very sorry for the late reply, but as there has been no more replies I'm closing this until further notice.
