### ISSUE TITLE
scoreboard now showing

### ISSUE THREAD

**Issue by PJPGames** [yPedx/SpigotBoard#33]
I was editing the scoreboard and got it to work then hopped off for the night and when i got back on the scoreboard was not showing! i restarted the server but its still not showing and when i do /scoreboard it says hidden...

**Comment by AdamFriska** [comment]
paste the logs on pastebin, or here in the comment section.
The Developer is inactive. I'm kinda disappointed too.

**Comment by yPedx** [comment]
This should be fixed in the newest version of SpigotBoard (v2.2.4).

**Comment by PJPGames** [comment]
got a different plugin
