### ISSUE TITLE
Does this plugin run Async?

### ISSUE THREAD

**Issue by Onyxtite** [yPedx/SpigotBoard#34]
I've taken a look at the source, and it doesn't seem to run Async, but to be honest, my java knowledge is limited, so I thought i'd make sure.
Suggestion: If it doesn't run async, please make it run async ;)

**Comment by yPedx** [comment]
You're right, it's not running async. But why would I make it async?

**Comment by Onyxtite** [comment]
Because anything that doesn't require to be in the main thread should be moved away from it, to reduce lagg. The main thread is usually the CPU bottleneck for servers, if you add extra load to it, you reduce performance, instead, if you run it on other threads, even if a lot of players are using a plugin, you will not generate performance issues, since the other threads aren't the bottleneck.

**Comment by yPedx** [comment]
I don't think it'll make much difference here though. Because of the Bukkit API being inaccessable from other threads, things must be performed on the main thread. Timers and such could be running on another thread, but it's contents must be performed on the main thread.

(Please correct me if I'm wrong.. I'm no genius o.O)

**Comment by Onyxtite** [comment]
I don't know what would be the ideal implementation for this, thats for you to find out (or not), however, when developing, you need to strive for performance even in a huge scale. For example What would happen if there were 1000 players online? Would thousands of timers not affect performance? Is there any way to improve that?  ( you should try to implement that logic to every aspect of every plugin, the less resources it uses to achieve the same functionality, the better the plugin is)

**Comment by yPedx** [comment]
I know tasks shouldn't all be put on the main thread, but it wouldn't matter too much when it's such a small project. If you take Featherboard as an example, it's a heavy plugin and most likely takes use of more than the main thread to keep out the lag.
