### ISSUE TITLE
{Money} not work it says N/A and i have essentials and vault installed. I use 1.14.3 on server.

### ISSUE THREAD

**Issue by kymppi** [yPedx/SpigotBoard#38]

**Comment by yPedx** [comment]
Do you have PlaceholderAPI installed?
Have you installed the necessary library from the ecloud in PlaceholerAPI?

**Comment by kymppi** [comment]
Oh i dont have ecloud library installed

**Comment by yPedx** [comment]
PlaceholderAPI comes with the ecloud service.

**Comment by kymppi** [comment]
I know but what is the necessary library

**Comment by yPedx** [comment]
If you do the in-game command /papi ecloud and install the extension called Vault, you should be good.

**Comment by kymppi** [comment]
it's still doesn't work. It says N/A

**Comment by kymppi** [comment]
I get it work. I don't use there %vault_eco_balance% {Money} won't work on me!
