### ISSUE TITLE
ScoreBoard Rank

### ISSUE THREAD

**Issue by coolkidharry1645** [yPedx/SpigotBoard#40]
Okay so I want my Group/Rank to show on the Scoreboard, but how????

**Comment by yPedx** [comment]
You need to use placeholders from PlaceholderAPI in Spigotboard.

**Comment by coolkidharry1645** [comment]
yaa but it wont work

**Comment by yPedx** [comment]
Are you sure you have the necessary plugins installed? (PlqceholderAPI, Vault and a permissions plugin). Also you might have to get the Vault extension from PlqceholderAPI's ecloud.

**Comment by yPedx** [comment]
Closed until further notice.
