### ISSUE TITLE
Board not updating after changing config

### ISSUE THREAD

**Issue by NightRider0** [yPedx/SpigotBoard#41]
After adding the plugin and reloading to generate the files I changed the config to what i wanted and saved it and reloaded the server, no change, restarted the server no change. i then removed the config from the folder and restarted again and it did not create a new config file either

**Comment by yPedx** [comment]
Reloading the server isn't very reliable. Use /spigotboard reload to reload the config file instead of restarting the whole server.

**Comment by NightRider0** [comment]
I tried that as well, with the same result

**Comment by yPedx** [comment]
Should be fixed in the newest version of SpigotBoard (3.0.0-BETA)
