### ISSUE TITLE
{Money} Variable/Placeholder not working

### ISSUE THREAD

**Issue by Eth-1** [yPedx/SpigotBoard#42]
Under the Balance section on my scoreboard for my server using SpigotBoard, it just says N/A, i am using essentialsX and Vault.

**Comment by yPedx** [comment]
Make sure you have the PlaceholerAPI extension for Vault installed too.

**Comment by Eth-1** [comment]
I have it, but I will update it if there is a new version, I’m on 1.15.2.
Another question, when I try changing the update thing in the config from 7 seconds to 1 second, even after I reload the plugin it still does 7 second updates, it is not really a big problem though.

Ethan

**Comment by finallight1** [comment]
I have a same problem. How do you install vault extension in placeholderapi?

**Comment by yPedx** [comment]
> I have it, but I will update it if there is a new version, I’m on 1.15.2. Another question, when I try changing the update thing in the config from 7 seconds to 1 second, even after I reload the plugin it still does 7 second updates, it is not really a big problem though. Ethan
> […](#)
> On Jan 26, 2020, at 7:26 AM, yPedx ***@***.***> wrote: ﻿ Make sure you have the PlaceholerAPI extension for Vault installed too. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
Using /reload to reload the scoreboard might reset changes. Try using **/spigotbaord reload** instead.

> I have a same problem. How do you install vault extension in placeholderapi?
I believe the command is **/papi ecloud download vault** to install the expansion.

I'll update the plugin soon, taking these issues into account.

**Comment by finallight1** [comment]
I installed it but money is still N/A. Hoping for another update soon!

**Comment by yPedx** [comment]
Should be handled in the newest version. All placeholders go through PlaceholderAPI now.
