### ISSUE TITLE
placeholder not working

### ISSUE THREAD

**Issue by finallight1** [yPedx/SpigotBoard#43]
Vault on PlaceholderAPI is installed (/papi ecloud donwload vault)
Also i installed vault and placeholder api and i have the newest version of spigotboard. 
It is not working.
![image](https://user-images.githubusercontent.com/60598537/76258720-cd5a9380-625c-11ea-9105-0961385b9902.png)

**Comment by yPedx** [comment]
Placeholder names from SpigotBoard have changed a bit, actually - you can find the new names [here](https://github.com/yPedx/SpigotBoard/wiki/Placeholders).

Do you have an economy plugin installed? No economy placeholders will be replaced if there's no economy plugin to fetch the balance from. Your other placeholders (%player_name% and %server_online%) seem to be coming from two other exentions for PAPI called Player and Server. Do you have those installed too?

**Comment by finallight1** [comment]
I have vault and balance is from essentials

**Comment by finallight1** [comment]
Kills and death also bot working, but the extension is installed

**Comment by yPedx** [comment]
Have you updated to the latest version of SpigotBoard? (3.0.1-BETA) Placeholders from SpigotBoard are no longer case sensitive, and should work fine. As for the placeholders from Vault, I'm not too sure as they work for me.

**Comment by finallight1** [comment]
I updated to the last one from spigot.org

**Comment by finallight1** [comment]
![image](https://user-images.githubusercontent.com/60598537/76404547-51149d00-638f-11ea-8931-cca16b5ab286.png)
Nickname and kills is now working but deaths doesn't. It is probably papi problem

**Comment by finallight1** [comment]
but i have essentials and balance, pay and other commands like this work.

**Comment by yPedx** [comment]
Have you tried the command **/papi parse <player> <placeholder>** ?
If this does replace the value, could you please provide me with your config file, as well as what Spigot version this is?

**Comment by finallight1** [comment]
I have all of the extentions yes, also i have paper not spigot

**Comment by finallight1** [comment]
Like /papi erase Qext %vault_eco_balance% ?

**Comment by yPedx** [comment]
Still, do you have the Vault **plugin**? The extension is not enough.
If Qext if your playerbane, the command is:
**/papi parse Qext %vault_eco_balance%**

**Comment by finallight1** [comment]
yeah i have vault

**Comment by finallight1** [comment]
Its Qexy i misspelled it. I’ll try

**Comment by finallight1** [comment]
Omg, i forgot to install vault. I thought i did because I have 2 different servers and I installed it on one of them lol
