### ISSUE TITLE
Request customization sponge

### ISSUE THREAD

**Issue by xXjojojXx** [yPedx/SpigotBoard#45]
could you make this plugin compatible with sponge sponge also supports API and placeholder '

**Comment by NICHOLASAW1608** [comment]
**Can You Make New PlaceHolder: Ping. For Checking Server Ping. Thx**

**Comment by yPedx** [comment]
> could you make this plugin compatible with sponge sponge also supports API and placeholder '
I do not plan to implement Sponge support, sorry.


> **Can You Make New PlaceHolder: Ping. For Checking Server Ping. Thx**
This placeholder is already available through PlaceholderAPI extensions.
