### ISSUE TITLE
Creating so much lagg

### ISSUE THREAD

**Issue by Ujjwalgarg210** [yPedx/SpigotBoard#48]
tps going down like 16

**Comment by MissGamerz** [comment]
good bug report so much info so much wow 

and it really doesn't its quite lightweight

**Comment by yPedx** [comment]
> tps going down like 16

I apologize for the late reply, however, I have not been able to reproduce this issue. Have you checked with your timings to find the source?

**Comment by yPedx** [comment]
Closing until further notice.
