### ISSUE TITLE
Scoreboard is showing every 2 secs

### ISSUE THREAD

**Issue by TheAlex52661** [yPedx/SpigotBoard#49]
I have a problem with the scoreboard and its like realoading every 2-3 seconds hides and shows up again

**Comment by yPedx** [comment]
> I have a problem with the scoreboard and its like realoading every 2-3 seconds hides and shows up again

Hi, what version are you having this issue with? Are there any errors in the console? I'll try and reproduce this, but I need to know the version.

**Comment by yPedx** [comment]
Unable to replicate this.. Will reopen if further information is added to the issue.
