### ISSUE TITLE
After updating to 2.1.5, I can no longer enter the game.

### ISSUE THREAD

**Issue by AncientTom** [yPedx/SpigotBoard#5]
Version 2.1.5 is broken. After logging onto the game. and the environment is loading, I loose connection with the server. There are no errors shown in the game log. It just shows that I have logged out. My client's launcher says that the server connection timed out.

**Comment by yPedx** [comment]
I'll be on it when I get home.

**Comment by yPedx** [comment]
Should be fixed in the new update (2.1.6),
