### ISSUE TITLE
Adding time spent on the server

### ISSUE THREAD

**Issue by SerMonPiteInc** [yPedx/SpigotBoard#50]
Add so the player can see how much time he spent on the server

**Comment by yPedx** [comment]
Unfortunately I do not plan to add playtime to this plugin, you're going to have to find a statistics plugin of some sort that supports PlaceholderAPI and use that inside the scoreboard

**Comment by SerMonPiteInc** [comment]
> Unfortunately I do not plan to add playtime to this plugin, you're going to have to find a statistics plugin of some sort that supports PlaceholderAPI and use that inside the scoreboard

But what's the problem? Please can you do this?

**Comment by yPedx** [comment]
> > Unfortunately I do not plan to add playtime to this plugin, you're going to have to find a statistics plugin of some sort that supports PlaceholderAPI and use that inside the scoreboard
> 
> But what's the problem? Please can you do this?

The purpose of this plugin was not to bring statistics, but a scoreboard solution, that's why there's not much reason to consider it.
