### ISSUE TITLE
How to change the color of spigotboard in Minecraft?

### ISSUE THREAD

**Issue by Pixnite** [yPedx/SpigotBoard#51]

**Comment by yPedx** [comment]
Hi!
To change the color of the scoreboard you can use the "&" character without the " in front of a number or character to use it. For example, &4 would be red color. Take a look at the attached image to see a list of color codes.![b2471b2e0f1c33180d0bb94f14a7126a__01.jpg](https://user-images.githubusercontent.com/26491360/219437090-31a81880-9a3f-49b4-aea3-89980a4ab570.jpg)
