### ISSUE TITLE
{Money} doesn't show the abount of money none of essentials or vault ;-;

### ISSUE THREAD

**Issue by TigerTBN** [yPedx/SpigotBoard#6]
Yea the title can explain my problem when i give {Money} in the config, it shows N/A every single time.
I tried with spaces and everything but it didn't work, it is still N/A.
The plugin works 100% perfect, but the thing that i want the plugin for, didn't work...
My luck is bad, no need to tell me, lol!
anyways can you please look into it, in any way i will really appreciate it, I have essentials and vault.
Thank you so much for the amazing plugin.

**Comment by yPedx** [comment]
Where did you download your Essentials from?

**Comment by yPedx** [comment]
Fixed in the latest version, thanks for the report!
