### ISSUE TITLE
The plugin does not work with coloretags?

### ISSUE THREAD

**Issue by Hxzxed** [yPedx/SpigotBoard#7]
if the plugin is active the colorenametags disappears and if the colorenametags is active the spigotboard disappears, any solution?

**Comment by yPedx** [comment]
What exactly do you mean with 'colornametags' ?

**Comment by Hxzxed** [comment]
An example
![image](https://user-images.githubusercontent.com/32908705/31783862-94d80bc6-b4b4-11e7-811f-0f6c62ed96d4.png)

**Comment by blackphreak** [comment]
The same issues here, but the author doesn't reply me anymore [ so I just close the issues :( ]
https://github.com/yPedx/SpigotBoard/issues/2

I provided a solution and I did my own experiment & test and it works.

**Comment by yPedx** [comment]
Using mainScoreboard was causing a lot of errors, thats why.

**Comment by blackphreak** [comment]
If you using my method to fix, it won't cause any errors.
At least I did it.

**Comment by blackphreak** [comment]
Or if you want, I can help you do fix this, but you need to provide me some of the source code.

**Comment by yPedx** [comment]
PM. Me on spigot.

**Comment by blackphreak** [comment]
My pull request created in here :
https://github.com/TheIndra55/SpigotBoard/pull/4
pls take a look
