### ISSUE TITLE
Hidden board not working

### ISSUE THREAD

**Issue by DevAmerok** [yPedx/SpigotBoard#8]
v2.1.7  Command to hide the board not working. Just freezes board.
Spigot 1.12.2

**Comment by yPedx** [comment]
I'll make sure to check it out, thank you for reporting :)

**Comment by yPedx** [comment]
Also, make sure you're not in a disabled world. Try relogging and see if it disappears.

**Comment by yPedx** [comment]
Fixed in the latest version: https://www.spigotmc.org/resources/spigotboard.47497/history

**Comment by DevAmerok** [comment]
Thanks

2017-10-21 9:50 GMT-04:00 yPedx <notifications@github.com>:
