### ISSUE TITLE
Add config setting to change time format

### ISSUE THREAD

**Issue by TheIndra55** [yPedx/SpigotBoard#9]
I would like to have a config option to change the {time} format so for example
`time: HH:mm`

You could simple change the hardcoded string in placeholders.java line 37 to a config option (with null check)
https://github.com/yPedx/SpigotBoard/blob/master/src/me/flower/utils/Placeholders.java#L37

**Comment by yPedx** [comment]
Done.
https://www.spigotmc.org/resources/spigotboard.47497/
